[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask-cors>=6.0.0",
    "flask>=3.1.1",
    "openai>=1.79.0",
    "tiktoken>=0.9.0",
    "pandas>=2.2.3",
]
